export const EventDetails = [
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-12",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-01",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-01",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-12",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-12",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-13",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-16",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-17",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
    {
      coverPhoto: "/images/events/cover.png",
      title: "Mukna Expo Launch & Interactive Mural Unveiling",
      location: "sawangan park",
      date: "2024-10-18",
      strTime: "8:00 AM",
      endTime: "12:00 PM",
    },
  ];