
export const cardsInfo = [
    {
      id: 1,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 2,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 3,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 4,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 5,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 6,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 7,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
    {
      id: 8,
      eventTitle: "Main event",
      startTime: "8:00 AM",
      endTime: "12:00 PM",
      location: "Sawangan park",
      eventAbout: "Mukna Expo Launch & Interactive Mural Unveiling",
    },
  ];
  